/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/theme/stargazer/stargazerTheme.ts
 * Command: astryx theme build src/theme/stargazer/stargazerTheme.ts
 * CLI: @astryxdesign/cli@0.6.2
 * Core: @astryxdesign/core@0.6.2
 */

/// <reference path="./stargazer.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
import type { IconRegistry } from '@astryxdesign/core/Icon';
export declare const stargazerIconRegistry: IconRegistry;
export declare const stargazerTheme: DefinedTheme;
